framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        prefix_seed: 'app'

        # The "app" cache stores to the filesystem by default.
        # The data in this cache should persist between deploys.
        # Other options include:

        # Redis
        #app: cache.adapter.redis
        #default_redis_provider: '%env(REDIS_URL)%'

        # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
        app: cache.adapter.filesystem
        system: cache.adapter.system

        # Namespaced pools use the above "app" backend by default
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
                default_lifetime: 3600
            doctrine.system_cache_pool:
                adapter: cache.system
                default_lifetime: 3600
            cache.validator:
                adapter: cache.system
                default_lifetime: 3600
            cache.serializer:
                adapter: cache.system
                default_lifetime: 3600
            cache.annotations:
                adapter: cache.system
                default_lifetime: 3600
            cache.property_info:
                adapter: cache.system
                default_lifetime: 3600
            cache.security_expression_language:
                adapter: cache.system
                default_lifetime: 3600
            cache.security_is_granted_attribute_expression_language:
                adapter: cache.system
                default_lifetime: 3600
