# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false
    handle_all_throwables: true
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
    php_errors:
        log: true
    cache:
        app: cache.adapter.filesystem
        system: cache.adapter.system
    assets:
        enabled: true
    fragments: { path: /_fragment }

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
