monolog:
    handlers:
        # Main application logs
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size: 50
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            formatter: monolog.formatter.json
        
        # Console output (for background processes)
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
        
        # Deprecation warnings
        deprecation:
            type: stream
            path: "%kernel.logs_dir%/deprecations.log"
            level: warning
            channels: [deprecation]
        
        # Security logs
        security:
            type: stream
            path: "%kernel.logs_dir%/security.log"
            level: info
            channels: [security]
            formatter: monolog.formatter.json
        
        # Performance/slow queries
        doctrine:
            type: stream
            path: "%kernel.logs_dir%/doctrine.log"
            level: warning
            channels: [doctrine]

